# We use c++ because it seems to be the only way to get ccache.
# ccache is necessary to rebuild V8 in not unreasonable amounts of time.
language: c++
cache:
  ccache: true
  directories:
   - .cache/  # For Parcel.
   - node_modules/
   - $V8WORKER2_OUT_PATH
env:
  global:
    - V8WORKER2_OUT_PATH=$HOME/v8worker2_out
    - PROTOBUF_ROOT=$HOME/protobuf
before_install: |
  eval "$(gimme 1.9.2)" # Use a newer version of Go.
  # Install protobuf
  export PATH=$PROTOBUF_ROOT/bin:$PATH
  if ! [ -x $PROTOBUF_ROOT/bin/protoc ]; then
    rm -rf $PROTOBUF_ROOT
    mkdir -p $PROTOBUF_ROOT
    pushd $PROTOBUF_ROOT
    wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip
    unzip protoc-3.1.0-linux-x86_64.zip
    popd
  fi
install:
 - mkdir -p $GOPATH/src/github.com/ry
 - ln -s `pwd` $GOPATH/src/github.com/ry/deno
 - go version
 - env
 - go get -d github.com/ry/v8worker2
 - $GOPATH/src/github.com/ry/v8worker2/build.py --use_ccache --out_path $V8WORKER2_OUT_PATH
 - go get -u github.com/golang/protobuf/proto
 - go get -u github.com/spf13/afero
 - go get -u github.com/golang/protobuf/protoc-gen-go
 - go get -u github.com/jteeuwen/go-bindata/...
 - yarn
script:
 - make lint
 - make test
